name: 'ci'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0

      - uses: 'wagoid/commitlint-github-action@v3'
        with:
          configFile: 'commitlint.config.js'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.2.0'
        with:
          node-version: 'lts/*'

      - run: 'npm --global install npm'
      - run: 'npm install'
      - run: 'npm run test'
